spring.datasource.url=jdbc:postgresql://ec2-52-3-2-245.compute-1.amazonaws.com:5432/dfbdfahdc041vj
spring.datasource.username=nduallvhcbvnju
spring.datasource.password=681614ede6ede5c3f0ba97d019a40df6d836a491a605ef0e5a1033fe358d0ddd

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=15

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true